strings = [
    "Available commands:                     ",
    "----------------------------------------",
    "OSINFO        : print system info       ",
    "CAT <addr>    : Print text from <addr>  ",
    "                until null terminator   ",
    "                                        ",
    "HELP          : show this help text     ",
    "TED <arg>     : Edit text at mem[arg:]  ",
    "COMPILE <a1> <a2>: Compile EASM text at ",
    "      mem[a1:] to executable at mem[a2:]",
    "                                        ",
    "RUN <addr>    : run mach. code at <addr>",
    "CALC <a> <op> <b>  : compute result     ",
    "           op={+,-,*,/,P(power),S(sqrt)}",
    "                                        ",
    "MEMEDIT <addr>: begin memedit at <addr> ",
    "PEEK <a>      : print mem[<a>]          ",
    "POKE <a> <val>: store <val> at <a>      ",
    "DUMP <a> <n>  : print decimal words     ",
    "HEXDUMP <a> <n>    : print hex words    ",
    "FILLMEM <start> <num> <val>: fill memory",
    "    From <start>, N=<num> with <val>    ",
    "                                        ",
    "CPYMEM <src> <dst> <len>: copy memory   ",
    "    mem[src:src+len] > mem[dst:dst+len] ",
    "                                        ",
    "PUZZLE        : Matt Parker 19 puzzle   ",
    "PRIMES        : print primes up to 300  ",
    "FIBONACCI     : print fibonacci values  ",
    "EMU           : shows some art          ",
    "ASTEROIDS     : play asteroids          ",
    "TETRIS        : play tetris             ",
    "TESTMEM       : List start/stop/size of ",
    "           every memory block with 100+ ",
    "           contiguous nulls             ",
    "                                        ",
    "ESH           : simple command prompt   ",
    "LIST          : show installed routines ",
    "CLS           : clear the screen        ",
    "OFF           : disable screen and halt ",
]

print('"' + "\\".join(strings) + '"')